### PR TITLE
Enhancements to build a static pacparser library and static pactester executable

### PR DESCRIPTION
**Pull request by mzpqnxow**
This was requested as a feature a while back in #28 and was declined with a reasonable explanation

I understand you may prefer to decline this PR but I figured there was a chance you would accept it since it doesn't require any extra effort on your part (well, not entirely true- you would have to "support" it, to some extent)

Either way, it's not important to me if you accept it. By having it here it will be documented for anyone who needs it, like the individual who opened up #28. I'm happy to save someone some time who may have the same unusual use-case as me :)

Thanks for the work you do on this project. Without it, I would have some really irritating problems to solve on production systems

### CODE REVIEW

**Comment by mzpqnxow** [comment]
@manugarg any interest in accepting this one? I added it because I needed a statically linked CNTLM executable. For that reason I pushed a static linking PR to one of the CNTLM forks and then used this patch as I needed PAC parsing in CNTLM

Thanks!

**Comment by jschwartzenberg** [comment]
The current PR seems to contain multiple things and I am not sure if the individual commits in it are really independent. If it would be merged as-is, that would make bisects less convenient for instance. I guess a rebased PR and possibly separate PRs for independent changes would make this more attractive to merge.

**Comment by jschwartzenberg** [comment]
The current PR seems to contain multiple things and I am not sure if the individual commits in it are really independent. If it would be merged as-is, that would make bisects less convenient for instance. I guess a rebased PR and possibly separate PRs for independent changes would make this more attractive to merge.

**Comment by manugarg** [comment]
Hello @mzpqnxow,  I am truly sorry I missed this PR. I was not able to pay much attention (except for security incidents) to the project for some time. I've now added an option to Makefile to build libpacarser.a (#205) (pretty independently, I ended up doing what you were doing), but we don't include static library in distribution as having both libpacarser.a and libpacarser.so in an installation is confusing.

**Comment by mzpqnxow** [comment]
> Hello @mzpqnxow,  I am truly sorry I missed this PR. I was not able to pay much attention (except for security incidents) to the project for some time, but I've been trying to be more proactive in last couple of years. I've now added an option to Makefile to build libpacarser.a (#205) (pretty independently, I ended up doing what you were doing), but we don't include static library in distribution as having both libpacarser.a and libpacarser.so in an installation is confusing. 

No worries!

I'm happy you did your own implementation because mine was really an "in a pinch" effort, to get a build to work to solve an immediate issue

Thanks

**Pull request closed without merging**
