### PR TITLE
Fix memory leak in str_replace.

### PR DESCRIPTION
**Pull request by manugarg**

### CODE REVIEW

**Comment by fralken** [comment]
Hello,
imo this PR is not correct, i.e., `free(tmporig);` doesn't work since `tmporig` has moved and doesn't point to the start of the buffer.
Since the buffer pointed by `orig` is not modified inside the function, there is no need to duplicate it.
So, instead of doing
```
    char *tmporig = malloc(strlen(orig) + 1); // Copy of orig that we work with
    tmporig = strcpy(tmporig, orig);
```
it should be enough doing instead
```
    char *tmporig = orig;
```
so there is no need to perform a `free()` in the end, and no memory leak is created.

**Comment by manugarg** [comment]
Thanks for catching this, @fralken! You're correct. As I said on the issue comment, I think we can skip copying the original string completely. Updated PR to reflect that.

**Comment by fralken** [comment]
Hello, are you planning to publish a new release with these fixes?

**Comment by manugarg** [comment]
Released - v.1.4.0.

**Pull request merged**
